[package]
name = "voodoo-store-python"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "_native"
path = "src/binding.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["extension-module", "abi3-py39", "multiple-pymethods"] }
voodoo-store-core = { path = "../voodoo-store-core" }
